spring.application.name=junglelog

spring.datasource.url=jdbc:mysql://localhost:3306/junglelog_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.expiration-ms=86400000

riot.api.base-url=https://euw1.api.riotgames.com

spring.profiles.active=local